name: Terraform Deployment
on:
  push:
    branches:
    - dev
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World!"
    - name: Clone Github repository
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: List files
      run: |
        ls -la
        pwd
        cat README.md
    - name: Installing Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.11.3"
    - name: Check Terraform Version
      run: terraform --version
