name: Terraform Deployment
on:
  push:
    branches:
    - dev
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World!"
    - name: Create files
      run: touch test.py
    - name: Clone Github repository
      uses: actions/checkout@v4
    - name: List files
      run: |
        ls -la
        pwd
