name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World!"
    - name: Print working directory
      run: pwd
    - name: Show files
      run: ls -la
  second-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print os
      run: |
        cat /etc/os-release
        whoami
